// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: hash.proto

package hash

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HashService_Sha1Message_FullMethodName   = "/hash.HashService/Sha1Message"
	HashService_Sha265Message_FullMethodName = "/hash.HashService/Sha265Message"
	HashService_Sha512Message_FullMethodName = "/hash.HashService/Sha512Message"
)

// HashServiceClient is the client API for HashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashServiceClient interface {
	Sha1Message(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Sha265Message(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
	Sha512Message(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type hashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHashServiceClient(cc grpc.ClientConnInterface) HashServiceClient {
	return &hashServiceClient{cc}
}

func (c *hashServiceClient) Sha1Message(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, HashService_Sha1Message_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) Sha265Message(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, HashService_Sha265Message_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashServiceClient) Sha512Message(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, HashService_Sha512Message_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashServiceServer is the server API for HashService service.
// All implementations must embed UnimplementedHashServiceServer
// for forward compatibility
type HashServiceServer interface {
	Sha1Message(context.Context, *Message) (*Message, error)
	Sha265Message(context.Context, *Message) (*Message, error)
	Sha512Message(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedHashServiceServer()
}

// UnimplementedHashServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHashServiceServer struct {
}

func (UnimplementedHashServiceServer) Sha1Message(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sha1Message not implemented")
}
func (UnimplementedHashServiceServer) Sha265Message(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sha265Message not implemented")
}
func (UnimplementedHashServiceServer) Sha512Message(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sha512Message not implemented")
}
func (UnimplementedHashServiceServer) mustEmbedUnimplementedHashServiceServer() {}

// UnsafeHashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashServiceServer will
// result in compilation errors.
type UnsafeHashServiceServer interface {
	mustEmbedUnimplementedHashServiceServer()
}

func RegisterHashServiceServer(s grpc.ServiceRegistrar, srv HashServiceServer) {
	s.RegisterService(&HashService_ServiceDesc, srv)
}

func _HashService_Sha1Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).Sha1Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_Sha1Message_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).Sha1Message(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_Sha265Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).Sha265Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_Sha265Message_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).Sha265Message(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashService_Sha512Message_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashServiceServer).Sha512Message(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashService_Sha512Message_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashServiceServer).Sha512Message(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// HashService_ServiceDesc is the grpc.ServiceDesc for HashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hash.HashService",
	HandlerType: (*HashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sha1Message",
			Handler:    _HashService_Sha1Message_Handler,
		},
		{
			MethodName: "Sha265Message",
			Handler:    _HashService_Sha265Message_Handler,
		},
		{
			MethodName: "Sha512Message",
			Handler:    _HashService_Sha512Message_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hash.proto",
}
